import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..", "..");
const entryPath = resolve(repoRoot, "packages", "ruviz-web", "src", "python-widget.ts");
const outPath = resolve(repoRoot, "python", "ruviz_py", "ruviz", "widget.js");
const wasmPath = resolve(
  repoRoot,
  "packages",
  "ruviz-web",
  "generated",
  "raw",
  "ruviz_web_raw_bg.wasm",
);

function createInlineWasmModule(base64) {
  return `
const base64 = ${JSON.stringify(base64)};

function decodeBase64Bytes(value) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);

  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }

  return bytes;
}

const wasmBytes = decodeBase64Bytes(base64);

export default wasmBytes;
`;
}

const wasmBase64 = Buffer.from(await Bun.file(wasmPath).arrayBuffer()).toString("base64");

function validateBundledSource(source: string) {
  const disallowedPatterns = [
    { pattern: /import\.meta\.url/, message: "widget bundle must not rely on import.meta.url" },
    { pattern: /session-worker/, message: "widget bundle must not reference session-worker" },
    {
      pattern: /^\s*import\b/m,
      message: "widget bundle must be self-contained with no remaining static imports",
    },
    {
      pattern: /^\s*export\b.*\bfrom\b/m,
      message: "widget bundle must be self-contained with no remaining re-exports",
    },
  ];

  for (const { pattern, message } of disallowedPatterns) {
    if (pattern.test(source)) {
      throw new Error(message);
    }
  }
}

await mkdir(dirname(outPath), { recursive: true });

const result = await Bun.build({
  entrypoints: [entryPath],
  format: "esm",
  minify: false,
  outfile: outPath,
  plugins: [
    {
      name: "inline-ruviz-wasm",
      setup(build) {
        build.onResolve({ filter: /^virtual:ruviz-wasm$/ }, () => ({
          namespace: "inline-ruviz-wasm",
          path: "virtual:ruviz-wasm",
        }));

        build.onLoad({ filter: /^virtual:ruviz-wasm$/, namespace: "inline-ruviz-wasm" }, () => ({
          contents: createInlineWasmModule(wasmBase64),
          loader: "js",
        }));
      },
    },
  ],
  target: "browser",
});

if (!result.success) {
  for (const log of result.logs) {
    console.error(log);
  }
  process.exit(1);
}

const bundledArtifacts = result.outputs.filter((output) => output.kind === "entry-point");
if (bundledArtifacts.length !== 1) {
  console.error(
    `build succeeded but expected exactly one entry-point output for ${outPath}; got: ${result.outputs
      .map((output) => output.path)
      .join(", ")}`,
  );
  process.exit(1);
}

const [bundledArtifact] = bundledArtifacts;
const bundledSource = await bundledArtifact.text();
validateBundledSource(bundledSource);
const banner = [
  "// Generated by python/scripts/build_widget_bundle.ts.",
  "// Do not edit this file directly; edit packages/ruviz-web/src/python-widget.ts instead.",
  "",
].join("\n");

await Bun.write(outPath, `${banner}${bundledSource}`);
