"""Type stubs for the compiled ``ruviz._native`` extension module.

Every method mirrors one ``#[pymethods]`` entry in ``bindings/python/src``.
Numeric arguments accept any float sequence; a C-contiguous ``float64`` NumPy
array is copied straight into ``Vec<f64>``. The ``style`` mappings carry the
validated per-series options.
"""

from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

from ._typing import StyleDict

#: Any accepted numeric vector; float64 arrays take the zero-conversion path.
_Numeric1D = Sequence[float] | npt.NDArray[np.float64]

#: Any accepted numeric matrix.
_Numeric2D = Sequence[Sequence[float]] | npt.NDArray[np.float64]

def version() -> str:
    """Return the compiled crate version."""

class NativeObservable1D:
    """Mutable numeric source shared with the renderer."""

    def __init__(self, values: _Numeric1D) -> None: ...
    def replace(self, values: _Numeric1D) -> None: ...
    def set_at(self, index: int, value: float) -> None: ...

_NumericSource = _Numeric1D | NativeObservable1D

class NativePlotHandle:
    """Incrementally built 2D plot backed by the core ``Plot`` builder."""

    def __init__(self) -> None: ...
    def size_px(self, width: int, height: int) -> None: ...
    def size(self, width_in: float, height_in: float) -> None: ...
    def dpi(self, dpi: int) -> None: ...
    def max_resolution(self, max_width: int, max_height: int) -> None: ...
    def font_size(self, points: float) -> None: ...
    def title_size(self, points: float) -> None: ...
    def font_family(self, family: str) -> None: ...
    def scale_typography(self, factor: float) -> None: ...
    def line_width_pt(self, points: float) -> None: ...
    def margin(self, fraction: float) -> None: ...
    def tight_layout_pad(self, points: float) -> None: ...
    def scientific_notation(self, enabled: bool) -> None: ...
    def fast(self, enabled: bool) -> None: ...
    def theme(self, theme: str) -> None: ...
    def ticks(self, enabled: bool) -> None: ...
    def title(self, title: str) -> None: ...
    def xlabel(self, label: str) -> None: ...
    def ylabel(self, label: str) -> None: ...
    def legend(self, position: str) -> None: ...
    def grid(self, enabled: bool) -> None: ...
    def xlim(self, min: float, max: float) -> None: ...
    def ylim(self, min: float, max: float) -> None: ...
    def xscale(self, scale: str, linthresh: float | None = None) -> None: ...
    def yscale(self, scale: str, linthresh: float | None = None) -> None: ...
    def line(
        self, x: _NumericSource, y: _NumericSource, style: StyleDict | None = None
    ) -> None: ...
    def scatter(
        self, x: _NumericSource, y: _NumericSource, style: StyleDict | None = None
    ) -> None: ...
    def bar(
        self,
        categories: Sequence[str],
        values: _NumericSource,
        style: StyleDict | None = None,
    ) -> None: ...
    def histogram(self, data: _NumericSource, style: StyleDict | None = None) -> None: ...
    def boxplot(self, data: _NumericSource, style: StyleDict | None = None) -> None: ...
    def heatmap(self, values: _Numeric1D, rows: int, cols: int) -> None: ...
    def error_bars(
        self,
        x: _NumericSource,
        y: _NumericSource,
        y_errors: _NumericSource,
        style: StyleDict | None = None,
    ) -> None: ...
    def error_bars_xy(
        self,
        x: _NumericSource,
        y: _NumericSource,
        x_errors: _NumericSource,
        y_errors: _NumericSource,
        style: StyleDict | None = None,
    ) -> None: ...
    def kde(self, data: _Numeric1D, style: StyleDict | None = None) -> None: ...
    def ecdf(self, data: _Numeric1D, style: StyleDict | None = None) -> None: ...
    def contour(
        self,
        x: _Numeric1D,
        y: _Numeric1D,
        z: _Numeric1D,
        style: StyleDict | None = None,
    ) -> None: ...
    def pie(self, values: _Numeric1D, labels: Sequence[str] | None) -> None: ...
    def radar(
        self,
        labels: Sequence[str],
        series: Sequence[tuple[str | None, _Numeric1D]],
    ) -> None: ...
    def violin(self, data: _Numeric1D, style: StyleDict | None = None) -> None: ...
    def polar_line(
        self,
        r: _Numeric1D,
        theta: _Numeric1D,
        style: StyleDict | None = None,
    ) -> None: ...
    def render_png_bytes(self) -> bytes: ...
    def render_png_bytes_uncached(self) -> bytes: ...
    def render_svg(self) -> str: ...
    def save(self, path: str) -> None: ...
    def show_native(self) -> None: ...

class NativePlot3DHandle:
    """Incrementally built 3D plot backed by the core 3D builders."""

    def __init__(self) -> None: ...
    def scatter3d(self, x: _Numeric1D, y: _Numeric1D, z: _Numeric1D) -> None: ...
    def line3d(self, x: _Numeric1D, y: _Numeric1D, z: _Numeric1D) -> None: ...
    def surface(self, x: _Numeric1D, y: _Numeric1D, z: _Numeric2D) -> None: ...
    def wireframe(self, x: _Numeric1D, y: _Numeric1D, z: _Numeric2D) -> None: ...
    def size_px(self, width: int, height: int) -> None: ...
    def dpi(self, dpi: int) -> None: ...
    def theme(self, theme: str) -> None: ...
    def title(self, title: str) -> None: ...
    def xlabel(self, label: str) -> None: ...
    def ylabel(self, label: str) -> None: ...
    def zlabel(self, label: str) -> None: ...
    def xlim(self, minimum: float, maximum: float) -> None: ...
    def ylim(self, minimum: float, maximum: float) -> None: ...
    def zlim(self, minimum: float, maximum: float) -> None: ...
    def azimuth_deg(self, degrees: float) -> None: ...
    def elevation_deg(self, degrees: float) -> None: ...
    def perspective_deg(self, vertical_fov_deg: float) -> None: ...
    def orthographic(self) -> None: ...
    def render_png_bytes(self) -> bytes: ...
    def render_svg(self) -> str: ...
    def save(self, path: str) -> None: ...
