"""Type stubs for the compiled ``ruviz._native`` extension module.

Every method mirrors one ``#[pymethods]`` entry in ``bindings/python/src``.
Numeric arguments are extracted as ``Vec<f64>``, so any float sequence works;
the ``style`` mappings carry the validated per-series options.
"""

from collections.abc import Sequence

from ._typing import StyleDict

def version() -> str:
    """Return the compiled crate version."""

class NativeObservable1D:
    """Mutable numeric source shared with the renderer."""

    def __init__(self, values: Sequence[float]) -> None: ...
    def replace(self, values: Sequence[float]) -> None: ...
    def set_at(self, index: int, value: float) -> None: ...

_NumericSource = Sequence[float] | NativeObservable1D

class NativePlotHandle:
    """Incrementally built 2D plot backed by the core ``Plot`` builder."""

    def __init__(self) -> None: ...
    def size_px(self, width: int, height: int) -> None: ...
    def theme(self, theme: str) -> None: ...
    def ticks(self, enabled: bool) -> None: ...
    def title(self, title: str) -> None: ...
    def xlabel(self, label: str) -> None: ...
    def ylabel(self, label: str) -> None: ...
    def legend(self, position: str) -> None: ...
    def grid(self, enabled: bool) -> None: ...
    def xlim(self, min: float, max: float) -> None: ...
    def ylim(self, min: float, max: float) -> None: ...
    def xscale(self, scale: str, linthresh: float | None = None) -> None: ...
    def yscale(self, scale: str, linthresh: float | None = None) -> None: ...
    def line(
        self, x: _NumericSource, y: _NumericSource, style: StyleDict | None = None
    ) -> None: ...
    def scatter(
        self, x: _NumericSource, y: _NumericSource, style: StyleDict | None = None
    ) -> None: ...
    def bar(
        self,
        categories: Sequence[str],
        values: _NumericSource,
        style: StyleDict | None = None,
    ) -> None: ...
    def histogram(self, data: _NumericSource, style: StyleDict | None = None) -> None: ...
    def boxplot(self, data: _NumericSource, style: StyleDict | None = None) -> None: ...
    def heatmap(self, values: Sequence[float], rows: int, cols: int) -> None: ...
    def error_bars(
        self,
        x: _NumericSource,
        y: _NumericSource,
        y_errors: _NumericSource,
        style: StyleDict | None = None,
    ) -> None: ...
    def error_bars_xy(
        self,
        x: _NumericSource,
        y: _NumericSource,
        x_errors: _NumericSource,
        y_errors: _NumericSource,
        style: StyleDict | None = None,
    ) -> None: ...
    def kde(self, data: Sequence[float], style: StyleDict | None = None) -> None: ...
    def ecdf(self, data: Sequence[float], style: StyleDict | None = None) -> None: ...
    def contour(
        self,
        x: Sequence[float],
        y: Sequence[float],
        z: Sequence[float],
        style: StyleDict | None = None,
    ) -> None: ...
    def pie(self, values: Sequence[float], labels: Sequence[str] | None) -> None: ...
    def radar(
        self,
        labels: Sequence[str],
        series: Sequence[tuple[str | None, Sequence[float]]],
    ) -> None: ...
    def violin(self, data: Sequence[float], style: StyleDict | None = None) -> None: ...
    def polar_line(
        self,
        r: Sequence[float],
        theta: Sequence[float],
        style: StyleDict | None = None,
    ) -> None: ...
    def render_png_bytes(self) -> bytes: ...
    def render_png_bytes_uncached(self) -> bytes: ...
    def render_svg(self) -> str: ...
    def save(self, path: str) -> None: ...
    def show_native(self) -> None: ...

class NativePlot3DHandle:
    """Incrementally built 3D plot backed by the core 3D builders."""

    def __init__(self) -> None: ...
    def scatter3d(self, x: Sequence[float], y: Sequence[float], z: Sequence[float]) -> None: ...
    def line3d(self, x: Sequence[float], y: Sequence[float], z: Sequence[float]) -> None: ...
    def surface(
        self, x: Sequence[float], y: Sequence[float], z: Sequence[Sequence[float]]
    ) -> None: ...
    def wireframe(
        self, x: Sequence[float], y: Sequence[float], z: Sequence[Sequence[float]]
    ) -> None: ...
    def size_px(self, width: int, height: int) -> None: ...
    def dpi(self, dpi: int) -> None: ...
    def theme(self, theme: str) -> None: ...
    def title(self, title: str) -> None: ...
    def xlabel(self, label: str) -> None: ...
    def ylabel(self, label: str) -> None: ...
    def zlabel(self, label: str) -> None: ...
    def xlim(self, minimum: float, maximum: float) -> None: ...
    def ylim(self, minimum: float, maximum: float) -> None: ...
    def zlim(self, minimum: float, maximum: float) -> None: ...
    def azimuth_deg(self, degrees: float) -> None: ...
    def elevation_deg(self, degrees: float) -> None: ...
    def perspective_deg(self, vertical_fov_deg: float) -> None: ...
    def orthographic(self) -> None: ...
    def render_png_bytes(self) -> bytes: ...
    def render_svg(self) -> str: ...
    def save(self, path: str) -> None: ...
